version: '3.8'

services:
  # 1. 数据库容器
  anime_db:
    image: postgres:16.4-alpine
    container_name: anime_db
    restart: always
    ports:
      - "9432:5432"  # 宿主机 9432，容器 5432
    environment:
      POSTGRES_USER: netflix
      POSTGRES_PASSWORD: netflix
      POSTGRES_DB: anime_vault
    volumes:
      - ./postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U netflix -d anime_vault"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # 2. API 容器 (.NET 10)
  anime_api:
    image: ghcr.io/setsuodu/animenetflix:v0.2.2
    container_name: animenetflix
    user: root 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8060:8060" # 映射 API 访问端口
    #volumes:
    #  - ./Anime.Api/wwwroot:/app/wwwroot  # 空的，映射不出来
    depends_on:
      anime_db:
        condition: service_healthy   # 关键！等 healthcheck 通过
      nginx:
        condition: service_started
    restart: unless-stopped        # 推荐加上，失败自动重启
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Shanghai
      # 重点：容器内部通信，Host 要写服务名 anime_db，端口用容器内的 5432
      - ConnectionStrings__DefaultConnection=Host=anime_db;Port=5432;Database=anime_vault;Username=netflix;Password=netflix

  # 3. Nginx 静态文件服务 (用于封面图)
  nginx:
    image: nginx:alpine
    container_name: anime_nginx
    # ★ 核心改动：强制以 root 运行。
    # 彻底解决你之前遇到的 chmod 权限问题，再也不会报 403 Forbidden
    user: root 
    restart: unless-stopped
    ports:
      - "8061:80"                    # 宿主机用 8080 访问图片（可改）
    volumes:
      # 挂载宿主机的 covers 文件夹
      - ./covers:/usr/share/nginx/html/covers:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

# ★ 声明具名卷，由 Docker 自动管理
volumes:
  anime_static: 